### ISSUE TITLE
Only see label 'meets basic integrity' 

### ISSUE THREAD

**Issue by MrHappy** [TheFreeman193/PIFS#11]
Running A14 on Google Pixel 7A.
Should I see the label 'device integrity' or is it only shown when it meets the device integrity?

**Comment by TheFreeman193** [comment]
Hi there,

After selecting a profile with the script, or copying one, you'll hopefully see `DEVICE_INTEGRITY` in the Play Integrity Checker app you're using (or the one in Play Store). This may take a number of tries.

If you aren't passing DEVICE after 20+ attempts, you may need to change the ABI directory the script is taking profiles from. See [the readme](https://github.com/TheFreeman193/PIFS/blob/main/README.md#the-json-file-i-tried-doesnt-work) for more details on this.

**Comment by MrHappy** [comment]
Ran it a few more times, now it shows up.
thanks
