### ISSUE TITLE
Document conversion to chiteroman format in option 2

### ISSUE THREAD

**Issue by asdfjkluiop** [TheFreeman193/PIFS#12]
As someone who is a bit weary of running scripts from the internet I opted to use option 2 and do this process manually but I run the chiteroman PIF and I couldn't figure out why no matter what fingerprint I used my play services kept crashing and integrity checks gave me "NO_INTEGRITY." Even worse than just basic. Eventually after checking the bug tracker I realized the files are in the wrong format and after extracting the bit of sed from your script I got this working with the first fingerprint I tried after previously going through about 10 of them. I spent quite a bit of time trying to track this down and for the future person doing it manually it'd be great if the conversion process was documented. Thanks for this collection!

**Comment by TheFreeman193** [comment]
This raises a good point - the documentation for manually copying profiles is indeed out of date. I'll update this section of the readme later today. Thanks for bringing this up!

**Comment by TheFreeman193** [comment]
Documentation has been updated with e6bc3f9.
