### ISSUE TITLE
Did i done something wrong ?

### ISSUE THREAD

**Issue by abdogm** [TheFreeman193/PIFS#2]
hi
i followed your instructions carefully and i got this warnings 
also there was no pif selected 
could you please tell me at least the way on how to do it correctly cuz i swear i am not sure if i did something wrong since i followed the instructions 
![Screenshot_20231228-114635_Termux (1)](https://github.com/TheFreeman193/PIFS/assets/72724405/09f7868a-cd6c-47d0-a482-f7a12a2bd13f)

**Comment by TheFreeman193** [comment]
Hi there, this doesn't appear to be your fault. It seems that the `sed` and `mv` commands in your environment aren't working as expected or are broken and my script relies on them for a number of string and file operations.

I am currently working on a new version of the script that uses *busybox* if available (which it should be with the most common root methods like Magisk and KSU). In the meantime, however, you can try manually aliasing the native commands in your environment to busybox ones.

If you're using Magisk:

```sh
for cmd in $(/data/adb/magisk/busybox --list | grep '[a-z0-9]'); do alias $cmd="/data/adb/magisk/busybox $cmd"; done
```

Or KSU (KernelSU):

```sh
for cmd in $(/data/adb/ksu/bin/busybox --list | grep '[a-z0-9]'); do alias $cmd="/data/adb/ksu/bin/busybox $cmd"; done
```

This only lasts for the current Termux/terminal emulator session.

**Comment by abdogm** [comment]
> If you're using Magisk:
> 
> ```shell
> for cmd in $(/data/adb/magisk/busybox --list | grep '[a-z0-9]'); do alias $cmd="/data/adb/magisk/busybox $cmd"; done
> ```

when i read ("$cmd="/data/adb/magisk/busybox") i realized that i have brutal busybox installed 
later i will try it again but with normal busybox and see what happens 
still not sure if different busybox build will effect on the script you made

**Comment by TheFreeman193** [comment]
> not sure if different busybox build will effect on the script you made

It's certainly possible if the native calls are redirected by aliases, symlinks, `$PATH` tweaks, overlays etc. to a busybox binary. You can check where a command is sourced with `type`, so

```sh
type sed
```

will tell you what'll get executed when you use that command.

**Comment by TheFreeman193** [comment]
Hi @abdogm, did you resolve your busybox problem?

**Comment by TheFreeman193** [comment]
@abdogm just following up - did you resolve your issue?

**Comment by 1cmoody23** [comment]
Hi, I was able to get it to work. I have to say at first it looked intimidating running scripts , etc but it did work, I can use google pay now. Thank you for the effort and your talent.
