### ISSUE TITLE
After running pickaprint, play intregrity can't be checked.

### ISSUE THREAD

**Issue by aqtoo** [TheFreeman193/PIFS#7]
Device : POCO F3
ROM : CRDroid (Android 14)
Root : KSU

After running pickaprint.sh with the osm0sis fork of Play Integrity Fix, any sort of method to check Play Integrity returns "API ERROR -17"

After reinstalling osm0sis on its own and not using pickaprint.sh, it works fine. After running the script once again it breaks.

**Comment by aqtoo** [comment]
I'll make sure to keep an eye on this and provide any logs I can if needed.

**Comment by TheFreeman193** [comment]
Some users have had issues with one of the additional properties I was including, namely `SDK_INT`. I updated the collection and script today, so could you re-download the script and try again please?

Error `-17` means a *transient error on the client* ([source](https://developer.android.com/reference/native/play/core/group/integrity)) which usually means DroidGuard crashed or didn't handle the request/response properly, but can sometimes result from sending too many requests in a short time.

Let me know what results you get with the new script.

**Comment by aqtoo** [comment]
After attempting to use the script again, I seemingly get a new error related to wget, it seems to persist even after reinstalling termux.

![Screenshot_20240106-130522_Termux](https://github.com/TheFreeman193/PIFS/assets/76844190/4bb56579-6ad9-4695-b375-76e4cb92fa43)

![Screenshot_20240106-130535_Termux](https://github.com/TheFreeman193/PIFS/assets/76844190/cc28f34e-d559-4ed7-a49a-3c3ee9961a63)

![Screenshot_20240106-130547_Termux](https://github.com/TheFreeman193/PIFS/assets/76844190/7fcf0ca4-f722-42df-89ec-6603a436b10a)
)

**Comment by TheFreeman193** [comment]
> ```text
> wget: TLS error from peer (alert code 80): 80
> wget: error getting response: Connection reset by peer
> ```

I'm not entirely sure why you're getting HTTPS errors downloading the collection archive, but I'm adding some `wget`/`curl` parameters to the next version of the script which might help. That should be out later today.

**Comment by aqtoo** [comment]
I'll keep an eye out for the update and test it when avaliable, if I forget please do remind me.

**Comment by TheFreeman193** [comment]
Hi @ac-tu, I've updated the script - could you check again please?

**Comment by aqtoo** [comment]
Seems to be all fixed on my end! Able to generate a successful working fingerprint after a few attempts, and it's able to update itself!
