### ISSUE TITLE
The pif.json file is incorrectly formatted for chiteroman

### ISSUE THREAD

**Issue by paour** [TheFreeman193/PIFS#9]
I've been trying to use your script to find a valid print on my device, and none worked.

`adb logcat` showed `PIF/Java: Couldn't parse JSON from Zygisk` whenever I tried a new one, so I started looking at the pif file, and it contained a dangling comma, which is not valid json.

```
…
  "FIRST_API_LEVEL": "25",
}
```

I tried fixing it, but between the very limited sed in busybox and my own ineptitude, I found it very hard to strip that dangling comma.

Here's a [very crude fix](https://github.com/TheFreeman193/PIFS/compare/main...paour:PIFS:main), but I know you get the gist and will find a more elegant solution.

**Comment by TheFreeman193** [comment]
This is interesting - I did implement a `sed` pattern to handle this when converting the profiles (natively in [osm0sis fork format](https://github.com/osm0sis/PlayIntegrityFork/blob/main/module/example.pif.json)) if the Chiteroman module is detected. I'll run some tests on my side to see if I can replicate the issue.

**Comment by TheFreeman193** [comment]
I can confirm this is happening due to a change in the format for the v1.3 collection where all values are wrapped as strings. The [existing code](https://github.com/TheFreeman193/PIFS/blob/main/pickaprint.sh#L456) wasn't updated to account for this.

I'll update the script with additional handling for all terminal commas.

**Comment by TheFreeman193** [comment]
This should be resolved with 3219619.

**Comment by paour** [comment]
Confirmed working (for me at least). Thanks for the quick fix!
